services:
  cache:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bookmarks
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  web:
    build: .
    command: ["python", "/code/manage.py", "runserver",
              "0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5432:5432"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=bookmarks
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
      - cache

